Updated Getting Started in README
Team-Falkor/falkor pull request #1
Opened 2024-09-09 14:13 UTC by dem0ngo

I updated it to show that the user needs rust installed and then I explained the command to build the executable. Feel free to change as needed.

2024-09-09 22:05 UTC, prostarz requested changes

2024-09-09 22:05 UTC, prostarz commented on README.md
> +5. Run `bun tauri:dev` to build the program.
change to run "Run `bun tauri:dev` to kick off the development server and watch your changes in real-time."

2024-09-12 13:55 UTC, dem0ngo commented
Sorry for the delay, I just updated the instructions to match your request.

2024-09-12 14:17 UTC, prostarz approved these changes

2024-09-12 14:18 UTC, merged